// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protos/types.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_ACTIVE      Status = 1
	Status_STATUS_INACTIVE    Status = 2
	Status_STATUS_PENDING     Status = 3
	Status_STATUS_SUSPENDED   Status = 4
	Status_STATUS_DELETED     Status = 5
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_ACTIVE",
		2: "STATUS_INACTIVE",
		3: "STATUS_PENDING",
		4: "STATUS_SUSPENDED",
		5: "STATUS_DELETED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_ACTIVE":      1,
		"STATUS_INACTIVE":    2,
		"STATUS_PENDING":     3,
		"STATUS_SUSPENDED":   4,
		"STATUS_DELETED":     5,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_types_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_protos_types_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_protos_types_proto_rawDescGZIP(), []int{0}
}

type EventState int32

const (
	EventState_STATE_SCHEDULED EventState = 0
	EventState_STATE_PUBLISHED EventState = 1
	EventState_STATE_DRAFT     EventState = 2
)

// Enum value maps for EventState.
var (
	EventState_name = map[int32]string{
		0: "STATE_SCHEDULED",
		1: "STATE_PUBLISHED",
		2: "STATE_DRAFT",
	}
	EventState_value = map[string]int32{
		"STATE_SCHEDULED": 0,
		"STATE_PUBLISHED": 1,
		"STATE_DRAFT":     2,
	}
)

func (x EventState) Enum() *EventState {
	p := new(EventState)
	*p = x
	return p
}

func (x EventState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventState) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_types_proto_enumTypes[1].Descriptor()
}

func (EventState) Type() protoreflect.EnumType {
	return &file_protos_types_proto_enumTypes[1]
}

func (x EventState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventState.Descriptor instead.
func (EventState) EnumDescriptor() ([]byte, []int) {
	return file_protos_types_proto_rawDescGZIP(), []int{1}
}

type EventStatus int32

const (
	EventStatus_STATUS_STARTED   EventStatus = 0
	EventStatus_STATUS_ENDED     EventStatus = 1
	EventStatus_STATUS_SCHEDULED EventStatus = 2
)

// Enum value maps for EventStatus.
var (
	EventStatus_name = map[int32]string{
		0: "STATUS_STARTED",
		1: "STATUS_ENDED",
		2: "STATUS_SCHEDULED",
	}
	EventStatus_value = map[string]int32{
		"STATUS_STARTED":   0,
		"STATUS_ENDED":     1,
		"STATUS_SCHEDULED": 2,
	}
)

func (x EventStatus) Enum() *EventStatus {
	p := new(EventStatus)
	*p = x
	return p
}

func (x EventStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_types_proto_enumTypes[2].Descriptor()
}

func (EventStatus) Type() protoreflect.EnumType {
	return &file_protos_types_proto_enumTypes[2]
}

func (x EventStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventStatus.Descriptor instead.
func (EventStatus) EnumDescriptor() ([]byte, []int) {
	return file_protos_types_proto_rawDescGZIP(), []int{2}
}

type AttendanceType int32

const (
	AttendanceType_TYPE_INVITED AttendanceType = 0
	AttendanceType_TYPE_CREATOR AttendanceType = 1
	AttendanceType_TYPE_ORGANIC AttendanceType = 2
)

// Enum value maps for AttendanceType.
var (
	AttendanceType_name = map[int32]string{
		0: "TYPE_INVITED",
		1: "TYPE_CREATOR",
		2: "TYPE_ORGANIC",
	}
	AttendanceType_value = map[string]int32{
		"TYPE_INVITED": 0,
		"TYPE_CREATOR": 1,
		"TYPE_ORGANIC": 2,
	}
)

func (x AttendanceType) Enum() *AttendanceType {
	p := new(AttendanceType)
	*p = x
	return p
}

func (x AttendanceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttendanceType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_types_proto_enumTypes[3].Descriptor()
}

func (AttendanceType) Type() protoreflect.EnumType {
	return &file_protos_types_proto_enumTypes[3]
}

func (x AttendanceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttendanceType.Descriptor instead.
func (AttendanceType) EnumDescriptor() ([]byte, []int) {
	return file_protos_types_proto_rawDescGZIP(), []int{3}
}

type AttendanceStatus int32

const (
	AttendanceStatus_STATUS_APPROVED  AttendanceStatus = 0
	AttendanceStatus_STATUS_DENIED    AttendanceStatus = 1
	AttendanceStatus_STATUS_REQUESTED AttendanceStatus = 2
)

// Enum value maps for AttendanceStatus.
var (
	AttendanceStatus_name = map[int32]string{
		0: "STATUS_APPROVED",
		1: "STATUS_DENIED",
		2: "STATUS_REQUESTED",
	}
	AttendanceStatus_value = map[string]int32{
		"STATUS_APPROVED":  0,
		"STATUS_DENIED":    1,
		"STATUS_REQUESTED": 2,
	}
)

func (x AttendanceStatus) Enum() *AttendanceStatus {
	p := new(AttendanceStatus)
	*p = x
	return p
}

func (x AttendanceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttendanceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_types_proto_enumTypes[4].Descriptor()
}

func (AttendanceStatus) Type() protoreflect.EnumType {
	return &file_protos_types_proto_enumTypes[4]
}

func (x AttendanceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttendanceStatus.Descriptor instead.
func (AttendanceStatus) EnumDescriptor() ([]byte, []int) {
	return file_protos_types_proto_rawDescGZIP(), []int{4}
}

type AttendanceEnum int32

const (
	AttendanceEnum_ENUM_ATTENDING AttendanceEnum = 0
	AttendanceEnum_ENUM_CHECKEDIN AttendanceEnum = 1
)

// Enum value maps for AttendanceEnum.
var (
	AttendanceEnum_name = map[int32]string{
		0: "ENUM_ATTENDING",
		1: "ENUM_CHECKEDIN",
	}
	AttendanceEnum_value = map[string]int32{
		"ENUM_ATTENDING": 0,
		"ENUM_CHECKEDIN": 1,
	}
)

func (x AttendanceEnum) Enum() *AttendanceEnum {
	p := new(AttendanceEnum)
	*p = x
	return p
}

func (x AttendanceEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttendanceEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_types_proto_enumTypes[5].Descriptor()
}

func (AttendanceEnum) Type() protoreflect.EnumType {
	return &file_protos_types_proto_enumTypes[5]
}

func (x AttendanceEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttendanceEnum.Descriptor instead.
func (AttendanceEnum) EnumDescriptor() ([]byte, []int) {
	return file_protos_types_proto_rawDescGZIP(), []int{5}
}

// Common pagination
type PageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortBy        string                 `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder     string                 `protobuf:"bytes,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"` // ASC, DESC
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_protos_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_protos_types_proto_rawDescGZIP(), []int{0}
}

func (x *PageRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *PageRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

type PageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    int32                  `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	HasMore       bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResponse) Reset() {
	*x = PageResponse{}
	mi := &file_protos_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResponse) ProtoMessage() {}

func (x *PageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResponse.ProtoReflect.Descriptor instead.
func (*PageResponse) Descriptor() ([]byte, []int) {
	return file_protos_types_proto_rawDescGZIP(), []int{1}
}

func (x *PageResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *PageResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_protos_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_protos_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_protos_types_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	State         EventState             `protobuf:"varint,4,opt,name=state,proto3,enum=types.EventState" json:"state,omitempty"`
	Status        EventStatus            `protobuf:"varint,5,opt,name=status,proto3,enum=types.EventStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_protos_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_protos_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_protos_types_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Event) GetState() EventState {
	if x != nil {
		return x.State
	}
	return EventState_STATE_SCHEDULED
}

func (x *Event) GetStatus() EventStatus {
	if x != nil {
		return x.Status
	}
	return EventStatus_STATUS_STARTED
}

func (x *Event) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Event) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Attendance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventId       string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Type          AttendanceType         `protobuf:"varint,4,opt,name=type,proto3,enum=types.AttendanceType" json:"type,omitempty"`
	Status        AttendanceStatus       `protobuf:"varint,5,opt,name=status,proto3,enum=types.AttendanceStatus" json:"status,omitempty"`
	Attendance    AttendanceEnum         `protobuf:"varint,6,opt,name=attendance,proto3,enum=types.AttendanceEnum" json:"attendance,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attendance) Reset() {
	*x = Attendance{}
	mi := &file_protos_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attendance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attendance) ProtoMessage() {}

func (x *Attendance) ProtoReflect() protoreflect.Message {
	mi := &file_protos_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attendance.ProtoReflect.Descriptor instead.
func (*Attendance) Descriptor() ([]byte, []int) {
	return file_protos_types_proto_rawDescGZIP(), []int{4}
}

func (x *Attendance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Attendance) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Attendance) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Attendance) GetType() AttendanceType {
	if x != nil {
		return x.Type
	}
	return AttendanceType_TYPE_INVITED
}

func (x *Attendance) GetStatus() AttendanceStatus {
	if x != nil {
		return x.Status
	}
	return AttendanceStatus_STATUS_APPROVED
}

func (x *Attendance) GetAttendance() AttendanceEnum {
	if x != nil {
		return x.Attendance
	}
	return AttendanceEnum_ENUM_ATTENDING
}

func (x *Attendance) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Attendance) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_protos_types_proto protoreflect.FileDescriptor

const file_protos_types_proto_rawDesc = "" +
	"\n" +
	"\x12protos/types.proto\x12\x05types\x1a\x1fgoogle/protobuf/timestamp.proto\"v\n" +
	"\vPageRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x17\n" +
	"\asort_by\x18\x03 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\tR\tsortOrder\"{\n" +
	"\fPageResponse\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\"\x81\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x98\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12'\n" +
	"\x05state\x18\x04 \x01(\x0e2\x11.types.EventStateR\x05state\x12*\n" +
	"\x06status\x18\x05 \x01(\x0e2\x12.types.EventStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xd9\x02\n" +
	"\n" +
	"Attendance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x12)\n" +
	"\x04type\x18\x04 \x01(\x0e2\x15.types.AttendanceTypeR\x04type\x12/\n" +
	"\x06status\x18\x05 \x01(\x0e2\x17.types.AttendanceStatusR\x06status\x125\n" +
	"\n" +
	"attendance\x18\x06 \x01(\x0e2\x15.types.AttendanceEnumR\n" +
	"attendance\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*\x86\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATUS_ACTIVE\x10\x01\x12\x13\n" +
	"\x0fSTATUS_INACTIVE\x10\x02\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x03\x12\x14\n" +
	"\x10STATUS_SUSPENDED\x10\x04\x12\x12\n" +
	"\x0eSTATUS_DELETED\x10\x05*G\n" +
	"\n" +
	"EventState\x12\x13\n" +
	"\x0fSTATE_SCHEDULED\x10\x00\x12\x13\n" +
	"\x0fSTATE_PUBLISHED\x10\x01\x12\x0f\n" +
	"\vSTATE_DRAFT\x10\x02*I\n" +
	"\vEventStatus\x12\x12\n" +
	"\x0eSTATUS_STARTED\x10\x00\x12\x10\n" +
	"\fSTATUS_ENDED\x10\x01\x12\x14\n" +
	"\x10STATUS_SCHEDULED\x10\x02*F\n" +
	"\x0eAttendanceType\x12\x10\n" +
	"\fTYPE_INVITED\x10\x00\x12\x10\n" +
	"\fTYPE_CREATOR\x10\x01\x12\x10\n" +
	"\fTYPE_ORGANIC\x10\x02*P\n" +
	"\x10AttendanceStatus\x12\x13\n" +
	"\x0fSTATUS_APPROVED\x10\x00\x12\x11\n" +
	"\rSTATUS_DENIED\x10\x01\x12\x14\n" +
	"\x10STATUS_REQUESTED\x10\x02*8\n" +
	"\x0eAttendanceEnum\x12\x12\n" +
	"\x0eENUM_ATTENDING\x10\x00\x12\x12\n" +
	"\x0eENUM_CHECKEDIN\x10\x01B4Z2github.com/mainheartng/event_project/protos;protosb\x06proto3"

var (
	file_protos_types_proto_rawDescOnce sync.Once
	file_protos_types_proto_rawDescData []byte
)

func file_protos_types_proto_rawDescGZIP() []byte {
	file_protos_types_proto_rawDescOnce.Do(func() {
		file_protos_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_types_proto_rawDesc), len(file_protos_types_proto_rawDesc)))
	})
	return file_protos_types_proto_rawDescData
}

var file_protos_types_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_protos_types_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protos_types_proto_goTypes = []any{
	(Status)(0),                   // 0: types.Status
	(EventState)(0),               // 1: types.EventState
	(EventStatus)(0),              // 2: types.EventStatus
	(AttendanceType)(0),           // 3: types.AttendanceType
	(AttendanceStatus)(0),         // 4: types.AttendanceStatus
	(AttendanceEnum)(0),           // 5: types.AttendanceEnum
	(*PageRequest)(nil),           // 6: types.PageRequest
	(*PageResponse)(nil),          // 7: types.PageResponse
	(*User)(nil),                  // 8: types.User
	(*Event)(nil),                 // 9: types.Event
	(*Attendance)(nil),            // 10: types.Attendance
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_protos_types_proto_depIdxs = []int32{
	11, // 0: types.User.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: types.User.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 2: types.Event.state:type_name -> types.EventState
	2,  // 3: types.Event.status:type_name -> types.EventStatus
	11, // 4: types.Event.created_at:type_name -> google.protobuf.Timestamp
	11, // 5: types.Event.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 6: types.Attendance.type:type_name -> types.AttendanceType
	4,  // 7: types.Attendance.status:type_name -> types.AttendanceStatus
	5,  // 8: types.Attendance.attendance:type_name -> types.AttendanceEnum
	11, // 9: types.Attendance.created_at:type_name -> google.protobuf.Timestamp
	11, // 10: types.Attendance.updated_at:type_name -> google.protobuf.Timestamp
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_protos_types_proto_init() }
func file_protos_types_proto_init() {
	if File_protos_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_types_proto_rawDesc), len(file_protos_types_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_types_proto_goTypes,
		DependencyIndexes: file_protos_types_proto_depIdxs,
		EnumInfos:         file_protos_types_proto_enumTypes,
		MessageInfos:      file_protos_types_proto_msgTypes,
	}.Build()
	File_protos_types_proto = out.File
	file_protos_types_proto_goTypes = nil
	file_protos_types_proto_depIdxs = nil
}
